### PR TITLE
Use model type in actables method call

### LINKED ISSUE #52: Actables class method does not restrict based on type
The `actables` class method does not restrict based on actable type, so will actually return incorrect results.

For example, consider the following structure (using Product (base), Pen and Book from the Readme)
```ruby
Pen.create(name: 'Parker', price: 1.0, color: 'Black')
Book.create(name: 'Mystery', price: 1.0, color: 'Black')
Pen.where(color: 'Black').actables # => returns 2 products, including also the book!
```

### PR DESCRIPTION
**Pull request by Taeir**
Fixes #52

### CODE REVIEW

**Comment by Taeir** [comment]
I don't really see what the test is failing on. It's showing identical comparisons as differences as far as I can see.

**Comment by chaadow** [comment]
@Taeir Thanks for the PR. and actually it took me a while to understand but wow in rails master they changed the "quote" character
image

from `'` to `’`

**Comment by chaadow** [comment]
I fixed the specs on master thanks!

**Comment by Taeir** [comment]
Totally didn't see that the ticks are indeed different, annoying but glad it's fixed now :)

**Pull request merged**
