### PR TITLE
Restore functionality that resolves belongs_to members in child classes when performing queries.

### PR DESCRIPTION
**Pull request by arielvalentin**
Fixes https://github.com/krautcomputing/active_record-acts_as/issues/18

### CODE REVIEW

**Comment by arielvalentin** [comment]
@manuelmeurer I was curious if you had any feedback for this PR. 

Do you have any capacity to review this in the next few days?

**Comment by manuelmeurer** [comment]
Hi @arielvalentin, thanks for your contribution and sorry for the delay!

The PR looks good! 👍 
But I don't think we need the `Rocket` and `StarShip` test models, could you use `Pen` and `PenCollection` instead?

**Comment by arielvalentin** [comment]
@manuelmeurer per your request I have updated the spec to use `Pen` and `PenCollection`

**Comment by arielvalentin** [comment]
@manuelmeurer Sorry to be a pest... but I could use your help with this.

**Comment by manuelmeurer** [comment]
3.0.1 is released!

**Comment by arielvalentin** [comment]
🚀 Thank you!!!

**Pull request merged**
