### PR TITLE
Handle kwargs in ruby 3 in methods delegated to supermodel

### PR DESCRIPTION
**Pull request by tindron**

### CODE REVIEW

**Comment by fonji** [comment]
@chaadow could you have a look on this?

**Comment by chaadow** [comment]
Thank you!

**Comment by chaadow** [comment]
@tindron @fonji released in [5.0.3](https://rubygems.org/gems/active_record-acts_as/versions/5.0.3)

**Comment by fonji** [comment]
Thanks @chaadow @tindron! :two_hearts:

**Pull request merged**
